on:
  push:
    branches:
      - main
  pull_request:

name: CI

env:
  DISABLE_V8_COMPILE_CACHE: 1

jobs:
  CI:
    name: CI_Node_${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20, 22]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run package tests
        run: yarn test:ci

      - name: Run linting
        run: yarn lint

      - name: Run Drizzle adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-drizzle

      - name: Run DynamoDB adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-dynamodb

      - name: Run KV adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-kv

      - name: Run Memory adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-memory

      - name: Run MongoDB adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-mongodb

      - name: Run MySQL adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-mysql

      - name: Run PostgreSQL adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-postgresql

      - name: Run Prisma adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-prisma

      - name: Run Redis adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-redis

      - name: Run SQLite adapter tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-sqlite
