on:
  push:
    branches:
      - main
  pull_request:

name: CI - PostgreSQL adapter

env:
  DISABLE_V8_COMPILE_CACHE: 1

jobs:
  CI:
    name: CI_Node_${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20, 22]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'yarn'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Run session storage tests
        run: yarn test:ci_sessions --filter=./packages/apps/session-storage/shopify-app-session-storage-postgresql
